default:
  options:
    retroarch.menu_driver: ozone
    retroarch.vrr_runloop_enable: false
    retroarch.video_max_swapchain_images: 3
    retroarch.video_adaptive_vsync: true
    hud_support: true
    retroarch.menu_scale_factor: 0.800000
    retroarch.menu_widget_scale_auto: false
    retroarch.menu_widget_scale_factor: 0.800000
    batterymode: highperformance
    powermode: highperformance

amiga1200:
  emulator: libretro
  core:     puae2021
amiga500:
  emulator: libretro
  core:     puae2021
amigacd32:
  emulator: libretro
  core:     puae2021
amigacdtv:
  emulator: libretro
  core:     puae2021
amigademo:
  emulator: libretro
  core:     puae2021
c20:
  emulator: libretro
  core:     vice_xvic
c64:
  emulator: libretro
  core:     vice_x64
c128:
  emulator: libretro
  core:     vice_x128
cplus4:
  emulator: libretro
  core:     vice_xplus4
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
model3:
  emulator: supermodel
  core:     supermodel-legacy
  options:
    videomode: max-720x576
    decorations: none
    hud_support: none
nds:
  emulator: drastic
  core:     drastic
pet:
  emulator: libretro
  core:     vice_xpet
psp:
  options:
    frameskip: automatic
psx:
  options:
    gfxbackend: vulkan
quake3:
  emulator: vkquake3
  core:     vkquake3
  options:
    videomode: max-1280x720
    decorations: none
    hud_support: none
scummvm:
  emulator: scummvm
  core:     scummvm
  options:
    decorations: none
    hud_support: none
sgb:
  emulator: libretro
  core:     mgba
gamecube:
  emulator: libretro
  core:     dolphin
  options:
    videomode: max-480x240
wii:
  emulator: libretro
  core:     dolphin
  options:
    videomode: max-480x240
wiiware:
  emulator: libretro
  core:     dolphin
  options:
    videomode: max-480x240
