default:
  options:
    ratio: "full"
    retroarch.menu_driver: rgui
    retroarch.audio_out_rate: 44100
    retroarch.audio_driver: tinyalsa

nds:
  emulator: drastic
  core:     drastic
psp:
  options:
    frameskip: automatic
psx:
  emulator: libretro
  core:     duckstation
  options:
    gpu_software: true
