default:
  options:
    retroarch.menu_driver: ozone
    retroarch.vrr_runloop_enable: false
    retroarch.video_max_swapchain_images: 3
    retroarch.video_adaptive_vsync: true
    hud_support: true
    retroarch.menu_scale_factor: 0.800000
    retroarch.menu_widget_scale_auto: false
    retroarch.menu_widget_scale_factor: 0.800000

c20:
  emulator: libretro
  core:     vice_xvic
c64:
  emulator: libretro
  core:     vice_x64
c128:
  emulator: libretro
  core:     vice_x128
cplus4:
  emulator: libretro
  core:     vice_xplus4
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
gamecube:
  emulator: libretro
  core:     dolphin
jaguar:
  emulator: virtualjaguar
  core:     virtualjaguar
model3:
  options:
    videomode: max-720x576
    decorations: none
    hud_support: none
nds:
  emulator: drastic
  core:     drastic
pet:
  emulator: libretro
  core:     vice_xpet
psp:
  options:
    frameskip: automatic
psx:
  options:
    gfxbackend: vulkan
sgb:
  emulator: libretro
  core:     mgba
wii:
  emulator: libretro
  core:     dolphin
wiiware:
  emulator: libretro
  core:     dolphin